dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - libcairo2-dev
            - libwebkitgtk-3.0-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test/slide_test
