dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      env:
        - COMPILER=g++-7
        - CMAKE=cmake
        - RUN_TESTS=true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libcairo2-dev
            - libwebkitgtk-3.0-dev
    - os: linux
      env:
        - PATH="/usr/lib/mxe/usr/bin/:$PATH"
        - COMPILER=i686-w64-mingw32.static-g++
        - CMAKE=i686-w64-mingw32.static-cmake
        - RUN_TESTS=false
      addons:
        apt:
          sources:
            - sourceline: 'deb http://pkg.mxe.cc/repos/apt/debian wheezy main'
              key_url: 'http://pkg.mxe.cc/repos/apt/conf/mxeapt.gpg'
          packages:
            - mxe-i686-w64-mingw32.static-gcc
            - mxe-i686-w64-mingw32.static-freetype
            - mxe-i686-w64-mingw32.static-cairo
            - mxe-x86-64-unknown-linux-gnu-cmake

script:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - mkdir build
  - cd build
  - ${CMAKE} ..
  - make
  - $RUN_TESTS && ./test/slide_test
