dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      env:
        - COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libcairo2-dev
            - libwebkitgtk-3.0-dev

script:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test/slide_test
