dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libcairo2-dev
            - libwebkitgtk-3.0-dev
          env:
            - CC=gcc-7
            - CXX=g++-7

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test/slide_test
